### ISSUE TITLE
Tiff files as input

### ISSUE THREAD

**Issue by akatav** [LieberInstitute/SUFI#1]
Hello
We have 2 photon microscopy images in .tiff format only. Can SUFI process tiff files ?

**Comment by vjysd** [comment]
Hey! Thanks for reaching out and using our package. I don't see a reason as to why tiff wouldn't work. The trick would be to make changes in main_FCLSU to load tiff (or tiff's) and make a lambda stack before calling FCLSU(...).  At the moment I don't have a script for this.

Are your single positives saved as tiff's as well?

**Comment by akatav** [comment]
Hi @vjysd 
Thanks for your reply. Actually I have only 2 channels with different wavelengths. It is a ````512*512*30*2```` array (30 being the number of frames). 
So, X=Y=512,Z=30,C=2. I think S=T=1 in this case. 
Which part of the if..else in main_FCLSU.m (line 57,line80) should be called with such an array ? 
I do not have seperate single positives for each channel. All I got is simply 2 arrays of size ````512*512*30````. Is it possible to use SUFI on such data? What is the value of P_vca in my case?

**Comment by vjysd** [comment]
Hey @akatav, apologies for the delay. In your case, P_vca would be 3 (i.e. 2 for channels and one for noise). Unfortunately, that becomes an underdetermined system where we are trying to resolve 3 unknowns from 2 channels. This could lead to poor performance in unmixing. A better solution is to use a clustering-based method such as k-means to unmix your data since the number of channels is low. A good starting point could be this package: https://doi.org/10.6084/m9.figshare.c.4537607
